# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies_management.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17movies_management.proto\x12\x11movies_management\"\x1f\n\x0fGetMovieRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"]\n\x0f\x41\x64\x64MovieRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tors\x18\x03 \x03(\t\x12\x10\n\x08\x64irector\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\x02\"o\n\x10\x41\x64\x64MovieResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tors\x18\x03 \x03(\t\x12\x10\n\x08\x64irector\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\x02\x12\x0f\n\x07message\x18\x06 \x01(\t\"[\n\rMovieResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tors\x18\x03 \x03(\t\x12\x10\n\x08\x64irector\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\x02\"%\n\x0fGetActorRequest\x12\x12\n\nactor_name\x18\x01 \x01(\t\"D\n\rActorResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nactor_name\x18\x02 \x01(\t\x12\x13\n\x0bmovie_names\x18\x03 \x03(\t\"2\n\x0cScoreRequest\x12\x12\n\nmovie_name\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\"P\n\rScoreResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nmovie_name\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x12\x0f\n\x07message\x18\x04 \x01(\t2\xe3\x02\n\rMoviesService\x12R\n\x08GetMovie\x12\".movies_management.GetMovieRequest\x1a .movies_management.MovieResponse\"\x00\x12R\n\x08GetActor\x12\".movies_management.GetActorRequest\x1a .movies_management.ActorResponse\"\x00\x12U\n\x08\x41\x64\x64Movie\x12\".movies_management.AddMovieRequest\x1a#.movies_management.AddMovieResponse\"\x00\x12S\n\x0c\x43hangeRating\x12\x1f.movies_management.ScoreRequest\x1a .movies_management.ScoreResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMOVIEREQUEST']._serialized_start=46
  _globals['_GETMOVIEREQUEST']._serialized_end=77
  _globals['_ADDMOVIEREQUEST']._serialized_start=79
  _globals['_ADDMOVIEREQUEST']._serialized_end=172
  _globals['_ADDMOVIERESPONSE']._serialized_start=174
  _globals['_ADDMOVIERESPONSE']._serialized_end=285
  _globals['_MOVIERESPONSE']._serialized_start=287
  _globals['_MOVIERESPONSE']._serialized_end=378
  _globals['_GETACTORREQUEST']._serialized_start=380
  _globals['_GETACTORREQUEST']._serialized_end=417
  _globals['_ACTORRESPONSE']._serialized_start=419
  _globals['_ACTORRESPONSE']._serialized_end=487
  _globals['_SCOREREQUEST']._serialized_start=489
  _globals['_SCOREREQUEST']._serialized_end=539
  _globals['_SCORERESPONSE']._serialized_start=541
  _globals['_SCORERESPONSE']._serialized_end=621
  _globals['_MOVIESSERVICE']._serialized_start=624
  _globals['_MOVIESSERVICE']._serialized_end=979
# @@protoc_insertion_point(module_scope)
